
import React,{useEffect,useState}from'react'
import{LOGO_DATA}from'./logoData'
import{supabase}from'./supabaseClient'
import{Home,FolderOpen,Users,Boxes,Archive,CalendarDays,Settings,Printer,Plus,Search,Save,Trash2,RefreshCw,Cloud,ShieldCheck,Zap,Headphones,Edit3}from'lucide-react'
const products=['FINESTRE','PERSIANE','TAPPARELLE','PORTONI BLINDATI','PORTE INTERNE','PORTE SEZIONALI']
const emptyCliente={nome:'',cognome:'',telefono:'',email:'',indirizzo:'',citta:'',note:''}
const emptyBase={cliente_id:'',cliente_nome:'',cliente_cognome:'',cliente_telefono:'',cliente_indirizzo:'',titolo:'',stato:'In lavorazione',data_sopralluogo:'',tecnico:''}
const modello={azienda:'',telaio:'',colore:'',maniglia:'',coprifili:'',tipologia_profilo:'',aletta:'',vetro:'',guarniture:'',posa:'',note_tecniche:''}
const righe=()=>Array.from({length:12},()=>({posizione:'',tipo:'',l:'',h:'',tipologia:'',apertura:'',note:''}))
const nuovaSezione=(tipo='FINESTRE')=>({id:Date.now()+Math.random(),tipo,modello:{...modello},righe:righe()})
export default function App(){
const[view,setView]=useState('dashboard'),[clienti,setClienti]=useState([]),[commesse,setCommesse]=useState([]),[cliente,setCliente]=useState(emptyCliente),[base,setBase]=useState(emptyBase),[sezioni,setSezioni]=useState([nuovaSezione()]),[query,setQuery]=useState(''),[status,setStatus]=useState(supabase?'Cloud pronto':'Cloud non configurato'),[editingId,setEditingId]=useState(null)
async function sync(){if(!supabase){setStatus('Cloud non configurato');return}const cr=await supabase.from('clienti').select('*').order('created_at',{ascending:false});const mr=await supabase.from('commesse').select('*').order('created_at',{ascending:false});if(cr.error||mr.error){setStatus('Errore cloud: '+(cr.error?.message||mr.error?.message));return}setClienti(cr.data||[]);setCommesse(mr.data||[]);setStatus('Cloud sincronizzato')}
useEffect(()=>{sync();if(!supabase)return;const ch=supabase.channel('live2').on('postgres_changes',{event:'*',schema:'public',table:'clienti'},sync).on('postgres_changes',{event:'*',schema:'public',table:'commesse'},sync).subscribe();return()=>supabase.removeChannel(ch)},[])
function nomeCliente(id){const c=clienti.find(x=>String(x.id)===String(id));return c?`${c.nome||''} ${c.cognome||''}`.trim():''}
function resetCommessa(){setBase(emptyBase);setSezioni([nuovaSezione()]);setEditingId(null)}
async function salvaCliente(){if(!cliente.nome&&!cliente.telefono){alert('Inserisci almeno nome o telefono');return}const{error}=await supabase.from('clienti').insert(cliente);if(error){alert('Errore cliente: '+error.message);return}setCliente(emptyCliente);await sync();setView('clienti')}
async function salvaCommessa(){if(!base.titolo){alert('Inserisci titolo commessa');return}let clienteId=base.cliente_id?Number(base.cliente_id):null;if(!clienteId&&(base.cliente_nome||base.cliente_telefono)){const{data,error}=await supabase.from('clienti').insert({nome:base.cliente_nome||null,cognome:base.cliente_cognome||null,telefono:base.cliente_telefono||null,indirizzo:base.cliente_indirizzo||null}).select().single();if(error){alert('Errore creazione cliente: '+error.message);return}clienteId=data.id}
const payload={cliente_id:clienteId,titolo:base.titolo,stato:base.stato,data_sopralluogo:base.data_sopralluogo||null,tecnico:base.tecnico||null,note:JSON.stringify({base,sezioni})}
let res=editingId?await supabase.from('commesse').update(payload).eq('id',editingId):await supabase.from('commesse').insert(payload)
if(res.error){alert('Errore commessa: '+res.error.message);return}resetCommessa();await sync();setView('commesse')}
function apriCommessa(c){try{const data=JSON.parse(c.note||'{}');setBase({...emptyBase,...data.base,cliente_id:c.cliente_id||data.base?.cliente_id||'',titolo:c.titolo||data.base?.titolo||'',stato:c.stato||data.base?.stato||'In lavorazione',data_sopralluogo:c.data_sopralluogo||data.base?.data_sopralluogo||'',tecnico:c.tecnico||data.base?.tecnico||''});setSezioni(data.sezioni?.length?data.sezioni:[nuovaSezione()]);setEditingId(c.id);setView('foglio')}catch{alert('Questa commessa non contiene ancora il nuovo formato modificabile')}}
async function delCliente(id){if(!confirm('Eliminare cliente?'))return;await supabase.from('clienti').delete().eq('id',id);sync()}
async function delCommessa(id){if(!confirm('Eliminare commessa?'))return;await supabase.from('commesse').delete().eq('id',id);sync()}
const cf=clienti.filter(x=>JSON.stringify(x).toLowerCase().includes(query.toLowerCase()));const mf=commesse.filter(x=>JSON.stringify(x).toLowerCase().includes(query.toLowerCase()))
return <div className="app"><Side view={view} setView={setView}/><main className="main">{view!=='foglio'&&<Top status={status} sync={sync}/>}
{view==='dashboard'&&<Dashboard clienti={clienti} commesse={commesse} setView={setView} reset={resetCommessa}/>}
{view==='clienti'&&<Clienti form={cliente} setForm={setCliente} rows={cf} q={query} setQ={setQuery} save={salvaCliente} del={delCliente}/>}
{view==='commesse'&&<Commesse rows={mf} q={query} setQ={setQuery} nomeCliente={nomeCliente} del={delCommessa} open={apriCommessa} setView={setView} reset={resetCommessa}/>}
{view==='foglio'&&<Foglio clienti={clienti} base={base} setBase={setBase} sezioni={sezioni} setSezioni={setSezioni} save={salvaCommessa} editing={!!editingId}/>}
{view==='prodotti'&&<Prodotti setView={setView} reset={resetCommessa} setSezioni={setSezioni}/>}
{view==='archivio'&&<Archivio clienti={clienti} commesse={commesse} nomeCliente={nomeCliente} open={apriCommessa}/>}
{view==='calendario'&&<section className="panel"><h1>Calendario</h1><p>Modulo calendario pronto per prossimo collegamento appuntamenti.</p></section>}
{view==='stampa'&&<Report clienti={clienti} commesse={commesse} nomeCliente={nomeCliente}/>}
{view==='impostazioni'&&<section className="panel"><h1>Impostazioni</h1><p>{status}</p><p>Versione 2: commesse riapribili, multi-prodotto, layout corretto.</p></section>}
</main></div>}
function Side({view,setView}){const items=[['dashboard','Dashboard',Home],['commesse','Commesse',FolderOpen],['clienti','Clienti',Users],['prodotti','Prodotti',Boxes],['archivio','Archivio',Archive],['calendario','Calendario',CalendarDays],['stampa','Stampa/PDF',Printer],['impostazioni','Impostazioni',Settings]];return <aside className="side no-print"><div className="logo">{LOGO_DATA&&<img src={LOGO_DATA}/>}</div>{items.map(([k,l,I])=><button key={k}className={view===k?'on':''}onClick={()=>setView(k)}><I/>{l}</button>)}</aside>}
function Top({status,sync}){return <header className="top no-print"><div><h1>Dashboard</h1><p>{status}</p></div><button onClick={sync}><RefreshCw/>Sincronizza</button></header>}
function Dashboard({clienti,commesse,setView,reset}){return <><div className="stats"><Card n={commesse.length} t="Commesse" s="Totali"/><Card n={clienti.length} t="Clienti" s="Registrati"/><Card n="LIVE" t="Cloud" s="Supabase"/><Card n="100%" t="Backup" s="Online"/></div><section className="panel"><h2>Commesse Recenti</h2>{commesse.slice(0,5).map(c=><div className="row"key={c.id}><b>{c.titolo}</b><span>{c.stato}</span></div>)}</section><section className="panel"><h2>Azioni Rapide</h2><div className="quick"><button className="red"onClick={()=>{reset();setView('foglio')}}><Plus/>Nuova Commessa</button><button className="navy"onClick={()=>setView('clienti')}><Plus/>Aggiungi Cliente</button><button className="red"onClick={()=>setView('prodotti')}><Boxes/>Aggiungi Prodotto</button><button className="navy"onClick={()=>window.print()}><Printer/>Stampa/PDF</button></div></section><div className="featurebar"><Feature icon={<Cloud/>}t="CLOUD"/><Feature icon={<ShieldCheck/>}t="SICURO"/><Feature icon={<Zap/>}t="VELOCE"/><Feature icon={<Headphones/>}t="ASSISTENZA"/></div></>}
function Card({n,t,s}){return <div className="card"><b>{n}</b><strong>{t}</strong><span>{s}</span></div>}
function Feature({icon,t}){return <div>{icon}<strong>{t}</strong><span>SOS INFISSI</span></div>}
function SearchBox({q,setQ}){return <div className="search"><Search/><input placeholder="Cerca..."value={q}onChange={e=>setQ(e.target.value)}/></div>}
function Clienti({form,setForm,rows,q,setQ,save,del}){return <section className="panel"><div className="head"><h1>Clienti</h1><SearchBox q={q}setQ={setQ}/></div><div className="form">{Object.keys(emptyCliente).map(k=>k==='note'?<textarea key={k}placeholder="Note"value={form[k]}onChange={e=>setForm({...form,[k]:e.target.value})}/>:<input key={k}placeholder={k.toUpperCase()}value={form[k]}onChange={e=>setForm({...form,[k]:e.target.value})}/>)}</div><button className="save"onClick={save}><Save/>Salva cliente</button><Table heads={['Nome','Telefono','Email','Indirizzo','']}rows={rows.map(c=>[`${c.nome||''} ${c.cognome||''}`,c.telefono,c.email,`${c.indirizzo||''} ${c.citta||''}`,<button className="danger"onClick={()=>del(c.id)}><Trash2/></button>])}/></section>}
function Commesse({rows,q,setQ,nomeCliente,del,open,setView,reset}){return <section className="panel"><div className="head"><h1>Commesse</h1><SearchBox q={q}setQ={setQ}/></div><button className="save"onClick={()=>{reset();setView('foglio')}}><Plus/>Nuova commessa</button><Table heads={['Cliente','Titolo','Stato','Tecnico','Data','Azioni']}rows={rows.map(c=>[nomeCliente(c.cliente_id)||'Non collegato',c.titolo,c.stato,c.tecnico,c.data_sopralluogo,<><button className="small"onClick={()=>open(c)}><Edit3/>Apri</button><button className="danger"onClick={()=>del(c.id)}><Trash2/></button></>])}/></section>}
function Foglio({clienti,base,setBase,sezioni,setSezioni,save,editing}){function addSection(){setSezioni([...sezioni,nuovaSezione()])}function changeSec(i,k,v){const a=[...sezioni];a[i]={...a[i],[k]:v};setSezioni(a)}function changeMod(i,k,v){const a=[...sezioni];a[i].modello={...a[i].modello,[k]:v};setSezioni(a)}function changeRow(si,ri,k,v){const a=[...sezioni];a[si].righe=[...a[si].righe];a[si].righe[ri]={...a[si].righe[ri],[k]:v};setSezioni(a)}function delSec(i){if(sezioni.length===1)return;setSezioni(sezioni.filter((_,x)=>x!==i))}return <div className="sheetWrap"><div className="floating no-print"><button onClick={addSection}>+ Aggiungi sezione prodotto</button><button onClick={save}>{editing?'Aggiorna':'Salva'} commessa</button><button onClick={()=>window.print()}>Stampa/PDF</button></div><section className="sheet"><div className="sheetLogo">{LOGO_DATA&&<img src={LOGO_DATA}/>}</div><h1>SOS INFISSI</h1><h2>COMMESSA RILIEVO MISURE</h2><p>Gli esperti della rimozione del vecchio telaio</p><div className="mini no-print"><select value={base.cliente_id}onChange={e=>setBase({...base,cliente_id:e.target.value})}><option value="">Cliente collegato</option>{clienti.map(c=><option key={c.id}value={c.id}>{c.nome} {c.cognome} - {c.telefono}</option>)}</select>{['cliente_nome','cliente_cognome','cliente_telefono','cliente_indirizzo','titolo','data_sopralluogo','tecnico'].map(k=><input key={k}type={k==='data_sopralluogo'?'date':'text'}placeholder={k.replaceAll('_',' ').toUpperCase()}value={base[k]}onChange={e=>setBase({...base,[k]:e.target.value})}/>)}</div><Info base={base}/>{sezioni.map((s,si)=><div className="productSection"key={s.id}><div className="sectionTitle"><h3>PRODOTTO {si+1} - {s.tipo}</h3><div className="no-print"><select value={s.tipo}onChange={e=>changeSec(si,'tipo',e.target.value)}>{products.map(p=><option key={p}>{p}</option>)}</select><button onClick={()=>delSec(si)}>Elimina sezione</button></div></div><Model m={s.modello}change={(k,v)=>changeMod(si,k,v)}/><h3>RIFERIMENTO MISURE - SEZIONE {si+1}</h3><table className="measure"><thead><tr>{['POSIZIONE','TIPO','L','H','TIPOLOGIA','APERTURA','NOTE'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{s.righe.map((r,ri)=><tr key={ri}>{Object.keys(r).map(k=><td key={k}><input value={r[k]}onChange={e=>changeRow(si,ri,k,e.target.value)}/></td>)}</tr>)}</tbody></table><h3>NOTE TECNICHE</h3><textarea className="notes"value={s.modello.note_tecniche}onChange={e=>changeMod(si,'note_tecniche',e.target.value)}/><div className="gridpaper">Schizzo tecnico / appunti disegno</div></div>)}</section></div>}
function Info({base}){return <table className="info"><tbody><tr><th>Cliente</th><td>{base.cliente_nome} {base.cliente_cognome}</td><th>Telefono</th><td>{base.cliente_telefono}</td></tr><tr><th>Indirizzo</th><td>{base.cliente_indirizzo}</td><th>Codice fiscale</th><td></td></tr><tr><th>Data sopralluogo</th><td>{base.data_sopralluogo}</td><th>Tecnico / Prev. n.</th><td>{base.tecnico}</td></tr></tbody></table>}
function Model({m,change}){const pairs=[['azienda','tipologia_profilo'],['telaio','aletta'],['colore','vetro'],['maniglia','guarniture'],['coprifili','posa']];return <table className="info"><tbody>{pairs.map(([a,b])=><tr key={a}><th>{a.toUpperCase()}</th><td><input value={m[a]}onChange={e=>change(a,e.target.value)}/></td><th>{b.toUpperCase()}</th><td><input value={m[b]}onChange={e=>change(b,e.target.value)}/></td></tr>)}</tbody></table>}
function Prodotti({setView,reset,setSezioni}){return <section className="panel"><h1>Prodotti</h1><div className="quick">{products.map(p=><button className="red"key={p}onClick={()=>{reset();setSezioni([nuovaSezione(p)]);setView('foglio')}}>{p}</button>)}</div></section>}
function Archivio({clienti,commesse,nomeCliente,open}){return <section className="panel"><h1>Archivio</h1><h2>Clienti</h2><Table heads={['Nome','Telefono','Indirizzo']}rows={clienti.map(c=>[`${c.nome||''} ${c.cognome||''}`,c.telefono,`${c.indirizzo||''} ${c.citta||''}`])}/><h2>Commesse</h2><Table heads={['Cliente','Titolo','Stato','Apri']}rows={commesse.map(c=>[nomeCliente(c.cliente_id),c.titolo,c.stato,<button className="small"onClick={()=>open(c)}>Apri</button>])}/></section>}
function Report({clienti,commesse,nomeCliente}){return <section className="report"><div className="reportHead">{LOGO_DATA&&<img src={LOGO_DATA}/>}<div><h1><span>SOS</span> INFISSI</h1><h2>REPORT</h2></div></div><Table heads={['Nome','Telefono']}rows={clienti.map(c=>[`${c.nome||''} ${c.cognome||''}`,c.telefono])}/><Table heads={['Cliente','Titolo','Stato']}rows={commesse.map(c=>[nomeCliente(c.cliente_id),c.titolo,c.stato])}/></section>}
function Table({heads,rows}){return <div className="table"><table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>):<tr><td colSpan={heads.length}>Nessun dato presente</td></tr>}</tbody></table></div>}
