
import React,{useEffect,useState}from'react'
import{LOGO_DATA}from'./logoData'
import{supabase}from'./supabaseClient'
import{Home,FolderOpen,Users,Boxes,Archive,CalendarDays,Settings,Printer,Plus,Search,Save,Trash2,RefreshCw,Cloud,ShieldCheck,Zap,Headphones}from'lucide-react'

const emptyCliente={nome:'',cognome:'',telefono:'',email:'',indirizzo:'',citta:'',note:''}
const emptyCommessa={cliente_id:'',cliente_nome:'',cliente_cognome:'',cliente_telefono:'',cliente_indirizzo:'',titolo:'',stato:'In lavorazione',data_sopralluogo:'',tecnico:'',note:'',azienda:'',telaio:'',colore:'',maniglia:'',coprifili:'',tipologia_profilo:'',aletta:'',vetro:'',guarniture:'',posa:'',note_tecniche:''}
const rows=()=>Array.from({length:12},()=>({posizione:'',tipo:'',l:'',h:'',tipologia:'',apertura:'',note:''}))
const products=['FINESTRE','PERSIANE','TAPPARELLE','PORTONI BLINDATI','PORTE INTERNE','PORTE SEZIONALI']

export default function App(){
const[view,setView]=useState('dashboard'),[clienti,setClienti]=useState([]),[commesse,setCommesse]=useState([]),[cliente,setCliente]=useState(emptyCliente),[commessa,setCommessa]=useState(emptyCommessa),[righe,setRighe]=useState(rows()),[prodotto,setProdotto]=useState('FINESTRE'),[query,setQuery]=useState(''),[status,setStatus]=useState(supabase?'Cloud pronto':'Cloud non configurato')
async function sync(){if(!supabase){setStatus('Cloud non configurato');return}const cr=await supabase.from('clienti').select('*').order('created_at',{ascending:false});const mr=await supabase.from('commesse').select('*').order('created_at',{ascending:false});if(cr.error||mr.error){setStatus('Errore cloud: '+(cr.error?.message||mr.error?.message));return}setClienti(cr.data||[]);setCommesse(mr.data||[]);setStatus('Cloud sincronizzato')}
useEffect(()=>{sync();if(!supabase)return;const ch=supabase.channel('live').on('postgres_changes',{event:'*',schema:'public',table:'clienti'},sync).on('postgres_changes',{event:'*',schema:'public',table:'commesse'},sync).subscribe();return()=>supabase.removeChannel(ch)},[])
function nomeCliente(id){const c=clienti.find(x=>String(x.id)===String(id));return c?`${c.nome||''} ${c.cognome||''}`.trim():''}
async function salvaCliente(){if(!cliente.nome&&!cliente.telefono){alert('Inserisci almeno nome o telefono');return}const{error}=await supabase.from('clienti').insert(cliente);if(error){alert('Errore cliente: '+error.message);return}setCliente(emptyCliente);await sync();setView('clienti')}
async function salvaCommessa(){if(!commessa.titolo){alert('Inserisci titolo commessa');return}let clienteId=commessa.cliente_id?Number(commessa.cliente_id):null;if(!clienteId&&(commessa.cliente_nome||commessa.cliente_telefono)){const{data,error}=await supabase.from('clienti').insert({nome:commessa.cliente_nome||null,cognome:commessa.cliente_cognome||null,telefono:commessa.cliente_telefono||null,indirizzo:commessa.cliente_indirizzo||null}).select().single();if(error){alert('Errore creazione cliente: '+error.message);return}clienteId=data.id}
const note=JSON.stringify({note:commessa.note,prodotto,modello:commessa,righe})
const{error}=await supabase.from('commesse').insert({cliente_id:clienteId,titolo:commessa.titolo,stato:commessa.stato,data_sopralluogo:commessa.data_sopralluogo||null,tecnico:commessa.tecnico||null,note})
if(error){alert('Errore commessa: '+error.message);return}setCommessa(emptyCommessa);setRighe(rows());await sync();setView('commesse')}
async function delCliente(id){if(!confirm('Eliminare cliente?'))return;await supabase.from('clienti').delete().eq('id',id);sync()}
async function delCommessa(id){if(!confirm('Eliminare commessa?'))return;await supabase.from('commesse').delete().eq('id',id);sync()}
const cf=clienti.filter(x=>JSON.stringify(x).toLowerCase().includes(query.toLowerCase()));const mf=commesse.filter(x=>JSON.stringify(x).toLowerCase().includes(query.toLowerCase()))
return <div className="app"><Side view={view} setView={setView}/><main className="main">{view!=='foglio'&&<Top status={status} sync={sync}/>}
{view==='dashboard'&&<Dashboard clienti={clienti} commesse={commesse} setView={setView}/>}
{view==='clienti'&&<Clienti form={cliente} setForm={setCliente} rows={cf} q={query} setQ={setQuery} save={salvaCliente} del={delCliente}/>}
{view==='commesse'&&<Commesse rows={mf} q={query} setQ={setQuery} nomeCliente={nomeCliente} del={delCommessa} setView={setView}/>}
{view==='foglio'&&<Foglio clienti={clienti} form={commessa} setForm={setCommessa} righe={righe} setRighe={setRighe} prodotto={prodotto} setProdotto={setProdotto} save={salvaCommessa}/>}
{view==='prodotti'&&<Prodotti setView={setView} prodotto={prodotto} setProdotto={setProdotto}/>}
{view==='archivio'&&<Archivio clienti={clienti} commesse={commesse} nomeCliente={nomeCliente}/>}
{view==='calendario'&&<Calendario/>}
{view==='stampa'&&<Report clienti={clienti} commesse={commesse} nomeCliente={nomeCliente}/>}
{view==='impostazioni'&&<section className="panel"><h1>Impostazioni</h1><p>{status}</p><p>Versione unificata: grafica + foglio rilievo + clienti + commesse cloud.</p></section>}
</main></div>}
function Side({view,setView}){const items=[['dashboard','Dashboard',Home],['commesse','Commesse',FolderOpen],['clienti','Clienti',Users],['prodotti','Prodotti',Boxes],['archivio','Archivio',Archive],['calendario','Calendario',CalendarDays],['stampa','Stampa/PDF',Printer],['impostazioni','Impostazioni',Settings]];return <aside className="side no-print"><div className="logo">{LOGO_DATA&&<img src={LOGO_DATA}/>}</div>{items.map(([k,l,I])=><button key={k}className={view===k?'on':''}onClick={()=>setView(k)}><I/>{l}</button>)}</aside>}
function Top({status,sync}){return <header className="top no-print"><div><h1>Dashboard</h1><p>{status}</p></div><button onClick={sync}><RefreshCw/>Sincronizza</button></header>}
function Dashboard({clienti,commesse,setView}){return <><div className="stats"><Card n={commesse.length} t="Commesse" s="Totali"/><Card n={clienti.length} t="Clienti" s="Registrati"/><Card n="LIVE" t="Cloud" s="Supabase"/><Card n="100%" t="Backup" s="Online"/></div><section className="panel"><h2>Commesse Recenti</h2>{commesse.slice(0,5).map(c=><div className="row"key={c.id}><b>{c.titolo}</b><span>{c.stato}</span></div>)}</section><section className="panel"><h2>Azioni Rapide</h2><div className="quick"><button className="red"onClick={()=>setView('foglio')}><Plus/>Nuova Commessa</button><button className="navy"onClick={()=>setView('clienti')}><Plus/>Aggiungi Cliente</button><button className="red"onClick={()=>setView('prodotti')}><Boxes/>Aggiungi Prodotto</button><button className="navy"onClick={()=>window.print()}><Printer/>Stampa/PDF</button></div></section><div className="featurebar"><Feature icon={<Cloud/>}t="CLOUD"/><Feature icon={<ShieldCheck/>}t="SICURO"/><Feature icon={<Zap/>}t="VELOCE"/><Feature icon={<Headphones/>}t="ASSISTENZA"/></div></>}
function Card({n,t,s}){return <div className="card"><b>{n}</b><strong>{t}</strong><span>{s}</span></div>}
function Feature({icon,t}){return <div>{icon}<strong>{t}</strong><span>SOS INFISSI</span></div>}
function SearchBox({q,setQ}){return <div className="search"><Search/><input placeholder="Cerca..."value={q}onChange={e=>setQ(e.target.value)}/></div>}
function Clienti({form,setForm,rows,q,setQ,save,del}){return <section className="panel"><div className="head"><h1>Clienti</h1><SearchBox q={q}setQ={setQ}/></div><div className="form">{Object.keys(emptyCliente).map(k=>k==='note'?<textarea key={k}placeholder="Note"value={form[k]}onChange={e=>setForm({...form,[k]:e.target.value})}/>:<input key={k}placeholder={k.toUpperCase()}value={form[k]}onChange={e=>setForm({...form,[k]:e.target.value})}/>)}</div><button className="save"onClick={save}><Save/>Salva cliente</button><Table heads={['Nome','Telefono','Email','Indirizzo','']}rows={rows.map(c=>[`${c.nome||''} ${c.cognome||''}`,c.telefono,c.email,`${c.indirizzo||''} ${c.citta||''}`,<button className="danger"onClick={()=>del(c.id)}><Trash2/></button>])}/></section>}
function Commesse({rows,q,setQ,nomeCliente,del,setView}){return <section className="panel"><div className="head"><h1>Commesse</h1><SearchBox q={q}setQ={setQ}/></div><button className="save"onClick={()=>setView('foglio')}><Plus/>Nuova commessa</button><Table heads={['Cliente','Titolo','Stato','Tecnico','Data','']}rows={rows.map(c=>[nomeCliente(c.cliente_id)||'Non collegato',c.titolo,c.stato,c.tecnico,c.data_sopralluogo,<button className="danger"onClick={()=>del(c.id)}><Trash2/></button>])}/></section>}
function Foglio({clienti,form,setForm,righe,setRighe,prodotto,setProdotto,save}){function rc(i,k,v){const a=[...righe];a[i]={...a[i],[k]:v};setRighe(a)}return <div className="sheetWrap"><div className="floating no-print"><select value={prodotto}onChange={e=>setProdotto(e.target.value)}>{products.map(p=><option key={p}>{p}</option>)}</select><button onClick={save}>Salva commessa</button><button onClick={()=>window.print()}>Stampa/PDF</button></div><section className="sheet"><div className="sheetLogo">{LOGO_DATA&&<img src={LOGO_DATA}/>}</div><h1>SOS INFISSI</h1><h2>MODELLO RILIEVO MISURE - {prodotto}</h2><p>Gli esperti della rimozione del vecchio telaio</p><div className="mini no-print"><select value={form.cliente_id}onChange={e=>setForm({...form,cliente_id:e.target.value})}><option value="">Cliente collegato</option>{clienti.map(c=><option key={c.id}value={c.id}>{c.nome} {c.cognome} - {c.telefono}</option>)}</select>{['cliente_nome','cliente_cognome','cliente_telefono','cliente_indirizzo','titolo','data_sopralluogo','tecnico'].map(k=><input key={k}type={k==='data_sopralluogo'?'date':'text'}placeholder={k.replaceAll('_',' ').toUpperCase()}value={form[k]}onChange={e=>setForm({...form,[k]:e.target.value})}/>)}</div><Info form={form}/><h3>MODELLO</h3><Model form={form}setForm={setForm}/><h3>RIFERIMENTO MISURE - SEZIONE 1</h3><table className="measure"><thead><tr>{['POSIZIONE','TIPO','L','H','TIPOLOGIA','APERTURA','NOTE'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{righe.map((r,i)=><tr key={i}>{Object.keys(r).map(k=><td key={k}><input value={r[k]}onChange={e=>rc(i,k,e.target.value)}/></td>)}</tr>)}</tbody></table><h3>NOTE TECNICHE</h3><textarea className="notes"value={form.note_tecniche}onChange={e=>setForm({...form,note_tecniche:e.target.value})}/><div className="gridpaper">Schizzo tecnico / appunti disegno</div></section></div>}
function Info({form}){return <table className="info"><tbody><tr><th>Cliente</th><td>{form.cliente_nome} {form.cliente_cognome}</td><th>Telefono</th><td>{form.cliente_telefono}</td></tr><tr><th>Indirizzo</th><td>{form.cliente_indirizzo}</td><th>Codice fiscale</th><td></td></tr><tr><th>Data sopralluogo</th><td>{form.data_sopralluogo}</td><th>Tecnico / Prev. n.</th><td>{form.tecnico}</td></tr></tbody></table>}
function Model({form,setForm}){const pairs=[['azienda','tipologia_profilo'],['telaio','aletta'],['colore','vetro'],['maniglia','guarniture'],['coprifili','posa']];return <table className="info"><tbody>{pairs.map(([a,b])=><tr key={a}><th>{a.toUpperCase()}</th><td><input value={form[a]}onChange={e=>setForm({...form,[a]:e.target.value})}/></td><th>{b.toUpperCase()}</th><td><input value={form[b]}onChange={e=>setForm({...form,[b]:e.target.value})}/></td></tr>)}</tbody></table>}
function Prodotti({setView,setProdotto}){return <section className="panel"><h1>Prodotti</h1><div className="quick">{products.map(p=><button className="red"key={p}onClick={()=>{setProdotto(p);setView('foglio')}}>{p}</button>)}</div></section>}
function Archivio({clienti,commesse,nomeCliente}){return <section className="panel"><h1>Archivio</h1><h2>Clienti</h2><Table heads={['Nome','Telefono','Indirizzo']}rows={clienti.map(c=>[`${c.nome||''} ${c.cognome||''}`,c.telefono,`${c.indirizzo||''} ${c.citta||''}`])}/><h2>Commesse</h2><Table heads={['Cliente','Titolo','Stato']}rows={commesse.map(c=>[nomeCliente(c.cliente_id),c.titolo,c.stato])}/></section>}
function Calendario(){return <section className="panel"><h1>Calendario</h1><p>Modulo calendario base pronto per prossimo collegamento agli appuntamenti.</p></section>}
function Report({clienti,commesse,nomeCliente}){return <section className="report"><div className="reportHead">{LOGO_DATA&&<img src={LOGO_DATA}/>}<div><h1><span>SOS</span> INFISSI</h1><h2>REPORT CLIENTI E COMMESSE</h2></div></div><Table heads={['Nome','Telefono']}rows={clienti.map(c=>[`${c.nome||''} ${c.cognome||''}`,c.telefono])}/><Table heads={['Cliente','Titolo','Stato']}rows={commesse.map(c=>[nomeCliente(c.cliente_id),c.titolo,c.stato])}/></section>}
function Table({heads,rows}){return <div className="table"><table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>):<tr><td colSpan={heads.length}>Nessun dato presente</td></tr>}</tbody></table></div>}
